version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  groups:
    eslint-dependencies:
      patterns:
        - "eslint"
        - "eslint-plugin-*"
        - "@eslint/*"
        - "eslint-config-*"
  open-pull-requests-limit: 10
  assignees:
  - tclindner
  labels:
  - 'dependencies :package:'
  versioning-strategy: increase
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
